# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(529, 402)
        Form.setMinimumSize(QtCore.QSize(529, 402))
        Form.setMaximumSize(QtCore.QSize(529, 402))
        self.mShowList = QtWidgets.QListWidget(Form)
        self.mShowList.setGeometry(QtCore.QRect(10, 10, 361, 381))
        self.mShowList.setObjectName("mShowList")
        self.mAddBtn = QtWidgets.QPushButton(Form)
        self.mAddBtn.setGeometry(QtCore.QRect(410, 100, 90, 31))
        self.mAddBtn.setObjectName("mAddBtn")
        self.mDeleteBtn = QtWidgets.QPushButton(Form)
        self.mDeleteBtn.setGeometry(QtCore.QRect(410, 160, 90, 31))
        self.mDeleteBtn.setObjectName("mDeleteBtn")
        self.mDeleteAllBtn = QtWidgets.QPushButton(Form)
        self.mDeleteAllBtn.setGeometry(QtCore.QRect(410, 220, 90, 31))
        self.mDeleteAllBtn.setObjectName("mDeleteAllBtn")
        self.mShowImageBtn = QtWidgets.QPushButton(Form)
        self.mShowImageBtn.setGeometry(QtCore.QRect(410, 280, 90, 31))
        self.mShowImageBtn.setObjectName("mShowImageBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "設定圖片"))
        self.mAddBtn.setText(_translate("Form", "新增圖片"))
        self.mDeleteBtn.setText(_translate("Form", "刪除圖片"))
        self.mDeleteAllBtn.setText(_translate("Form", "刪除全部"))
        self.mShowImageBtn.setText(_translate("Form", "顯示選取圖片"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
