# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'type.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.mPngRadio = QtWidgets.QRadioButton(Form)
        self.mPngRadio.setGeometry(QtCore.QRect(190, 60, 83, 16))
        self.mPngRadio.setObjectName("mPngRadio")
        self.mJpgRadio = QtWidgets.QRadioButton(Form)
        self.mJpgRadio.setGeometry(QtCore.QRect(190, 100, 83, 16))
        self.mJpgRadio.setObjectName("mJpgRadio")
        self.mBmpRadio = QtWidgets.QRadioButton(Form)
        self.mBmpRadio.setGeometry(QtCore.QRect(190, 140, 83, 16))
        self.mBmpRadio.setObjectName("mBmpRadio")
        self.mConfirmBtn = QtWidgets.QPushButton(Form)
        self.mConfirmBtn.setGeometry(QtCore.QRect(150, 230, 81, 31))
        self.mConfirmBtn.setObjectName("mConfirmBtn")
        self.mDefaultRadio = QtWidgets.QRadioButton(Form)
        self.mDefaultRadio.setGeometry(QtCore.QRect(190, 180, 111, 16))
        self.mDefaultRadio.setObjectName("mDefaultRadio")
        self.mTypeHint = QtWidgets.QLabel(Form)
        self.mTypeHint.setGeometry(QtCore.QRect(90, 120, 81, 16))
        self.mTypeHint.setObjectName("mTypeHint")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "設定轉檔格式"))
        self.mPngRadio.setText(_translate("Form", "PNG"))
        self.mJpgRadio.setText(_translate("Form", "JPG"))
        self.mBmpRadio.setText(_translate("Form", "BMP"))
        self.mConfirmBtn.setText(_translate("Form", "確認格式"))
        self.mDefaultRadio.setText(_translate("Form", "Default (不更改)"))
        self.mTypeHint.setText(_translate("Form", "設定存檔格式"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
