# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mChooseBtn = QtWidgets.QPushButton(self.centralwidget)
        self.mChooseBtn.setGeometry(QtCore.QRect(40, 210, 171, 31))
        self.mChooseBtn.setObjectName("mChooseBtn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 40, 321, 441))
        self.label.setObjectName("label")
        self.mFlipBtn = QtWidgets.QPushButton(self.centralwidget)
        self.mFlipBtn.setGeometry(QtCore.QRect(240, 210, 171, 31))
        self.mFlipBtn.setObjectName("mFlipBtn")
        self.mCutBtn = QtWidgets.QPushButton(self.centralwidget)
        self.mCutBtn.setGeometry(QtCore.QRect(240, 260, 171, 31))
        self.mCutBtn.setObjectName("mCutBtn")
        self.mResizeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.mResizeBtn.setGeometry(QtCore.QRect(240, 310, 171, 31))
        self.mResizeBtn.setObjectName("mResizeBtn")
        self.mTypeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.mTypeBtn.setGeometry(QtCore.QRect(40, 260, 171, 31))
        self.mTypeBtn.setObjectName("mTypeBtn")
        self.mTypeHint = QtWidgets.QLabel(self.centralwidget)
        self.mTypeHint.setGeometry(QtCore.QRect(50, 310, 171, 31))
        self.mTypeHint.setObjectName("mTypeHint")
        self.mTransBar = QtWidgets.QProgressBar(self.centralwidget)
        self.mTransBar.setGeometry(QtCore.QRect(90, 500, 641, 21))
        self.mTransBar.setProperty("value", 24)
        self.mTransBar.setObjectName("mTransBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "批量圖片處理器 ver.0"))
        self.mChooseBtn.setText(_translate("MainWindow", "選取圖片"))
        self.label.setText(_translate("MainWindow", "尚未選取圖片"))
        self.mFlipBtn.setText(_translate("MainWindow", "翻轉圖片"))
        self.mCutBtn.setText(_translate("MainWindow", "剪裁圖片"))
        self.mResizeBtn.setText(_translate("MainWindow", "變更大小"))
        self.mTypeBtn.setText(_translate("MainWindow", "設定轉檔格式"))
        self.mTypeHint.setText(_translate("MainWindow", "目前轉檔格式設定為: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
