# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 600)
        MainWindow.setMinimumSize(QtCore.QSize(798, 600))
        MainWindow.setMaximumSize(QtCore.QSize(798, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mSystemHint = QtWidgets.QLabel(self.centralwidget)
        self.mSystemHint.setGeometry(QtCore.QRect(220, 340, 81, 31))
        self.mSystemHint.setObjectName("mSystemHint")
        self.mFlipBtn = QtWidgets.QPushButton(self.centralwidget)
        self.mFlipBtn.setGeometry(QtCore.QRect(430, 200, 171, 31))
        self.mFlipBtn.setObjectName("mFlipBtn")
        self.mCutBtn = QtWidgets.QPushButton(self.centralwidget)
        self.mCutBtn.setGeometry(QtCore.QRect(430, 250, 171, 31))
        self.mCutBtn.setObjectName("mCutBtn")
        self.mResizeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.mResizeBtn.setGeometry(QtCore.QRect(430, 300, 171, 31))
        self.mResizeBtn.setObjectName("mResizeBtn")
        self.mTypeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.mTypeBtn.setGeometry(QtCore.QRect(170, 250, 171, 31))
        self.mTypeBtn.setObjectName("mTypeBtn")
        self.mTypeHint = QtWidgets.QLabel(self.centralwidget)
        self.mTypeHint.setGeometry(QtCore.QRect(180, 300, 171, 31))
        self.mTypeHint.setObjectName("mTypeHint")
        self.mTransBar = QtWidgets.QProgressBar(self.centralwidget)
        self.mTransBar.setGeometry(QtCore.QRect(90, 500, 641, 21))
        self.mTransBar.setProperty("value", 24)
        self.mTransBar.setObjectName("mTransBar")
        self.mShowBtn = QtWidgets.QPushButton(self.centralwidget)
        self.mShowBtn.setGeometry(QtCore.QRect(170, 200, 171, 31))
        self.mShowBtn.setObjectName("mShowBtn")
        self.mProgressHint = QtWidgets.QLabel(self.centralwidget)
        self.mProgressHint.setGeometry(QtCore.QRect(360, 460, 91, 21))
        self.mProgressHint.setText("")
        self.mProgressHint.setObjectName("mProgressHint")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "批量圖片處理器 ver.0"))
        self.mSystemHint.setText(_translate("MainWindow", "尚未選取圖片"))
        self.mFlipBtn.setText(_translate("MainWindow", "翻轉圖片"))
        self.mCutBtn.setText(_translate("MainWindow", "剪裁圖片"))
        self.mResizeBtn.setText(_translate("MainWindow", "變更大小"))
        self.mTypeBtn.setText(_translate("MainWindow", "設定轉檔格式"))
        self.mTypeHint.setText(_translate("MainWindow", "目前轉檔格式設定為: "))
        self.mShowBtn.setText(_translate("MainWindow", "設定圖片"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
