# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imageshow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(477, 434)
        Form.setMinimumSize(QtCore.QSize(477, 434))
        Form.setMaximumSize(QtCore.QSize(6000, 6001))
        self.mShowImage = QtWidgets.QLabel(Form)
        self.mShowImage.setGeometry(QtCore.QRect(0, 0, 471, 431))
        self.mShowImage.setObjectName("mShowImage")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "顯示所選圖片"))
        self.mShowImage.setText(_translate("Form", "顯示圖片"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
